### ISSUE TITLE
장소 단건 조회 기능 구현

### ISSUE THREAD

**Issue by Wo-ogie** [Zelusik/server-main#12]
## 🔥 Issue
"가게 상세" 페이지에서 사용할 장소 단건조회 API를 구현한다.

## ✅ TODO
- [x]  장소 단건 조회 API 구현.
  - [x] 장소의 PK 값으로 단건조회하는 기능 구현
  - [ ] 장소의 `kakaoPid` 값으로 단건조회하는 기능 구현

**Comment by Wo-ogie** [comment]
`kakaoPid`로 단건조회하는 기능을 새로 구현하고자 내용 추가하여 issue reopen
