### ISSUE TITLE
Redis를 이용해 자주 조회되는 데이터 caching

### ISSUE THREAD

**Issue by Wo-ogie** [Zelusik/server-main#196]
## 🔥 Issue
Redis를 이용해 자주 조회되는 데이터 caching

## ✅ TODO
- [x] Redis cache 설정
- [x] 큐레이션 목록 데이터 caching
- [x] JWT token을 parsing 할 때 조회하는 회원 데이터 caching

**Comment by Wo-ogie** [comment]
추가할 설정이 있어 issue reopen
