### ISSUE TITLE
회원 역할 부여 및 일부 API의 접근 권한 설정

### ISSUE THREAD

**Issue by Wo-ogie** [Zelusik/server-main#206]
## 🔥 Issue
현재 모든 회원들이 권한이 구분되어있지 않고 `USER`로 통일되어있다.
일부 기능의 경우 관리자만 접근할 수 있도록 하는 것이 바람직하므로, 
회원에게 역할을 부여하고 일부 API는 역할에 따른 접근 권한을 설정하고자 한다.

## ✅ TODO
- [x] `Member` entity에 역할(`RoleType`) 추가
  - [x] 이에 따른 `UserPrincipal`에 변경사항 반영
- [x] 접근 권한 제한이 필요한 API 점검 후 접근 제어 설정
