### ISSUE TITLE
메뉴 직접 등록하기(추가하기) 기능 구현

### ISSUE THREAD

**Issue by Wo-ogie** [Zelusik/server-main#237]
# 🔥 Issue
장소 메뉴 목록 데이터에 사용자가 직접 메뉴를 등록할 수 있도록 기능을 추가한다.
이 때, 중복된 메뉴는 추가 등록할 수 없으며, "중복"의 기준은 다음과 같다.
- 완전히 동일한 문자열 (ex. `김치찌개` == `김치찌개`)
- 띄어쓰기를 제외하면 동일한 문자열 (ex. `김치찌개` == `김치 찌개`)

# ✅ TODO
- [x] 메뉴 직접 등록하기(추가하기) 기능 구현
  - [x] `PlaceMenus`의 `menus` field를 overwrite하는 `PUT` API 구현
  - [x] 추가할 하나의 메뉴만 전달하여 기존 `menus` field에 추가하는 `PATCH` API 구현
