### ISSUE TITLE
메뉴 데이터 저장(초기화) 기능 구현

### ISSUE THREAD

**Issue by Wo-ogie** [Zelusik/server-main#239]
# 🔥 Issue
메뉴 목록 저장(초기화) API를 구현한다.
Scraping server에 메뉴 데이터를 요청하여 필요한 데이터를 응답받은 뒤, 해당 데이터를 장소의 메뉴 데이터로하여 DB에 저장한다.

# ✅ TODO
- [x] 특정 장소에 대한 메뉴 데이터 저장(초기화) 구현
  - [x] 장소 메뉴 Entity, repository class 정의
  - [x] 관련 business logic 구현
  - [x] API 구현

**Comment by Wo-ogie** [comment]
`kakaoPid`로 장소를 식별하여 메뉴 데이터를 생성하는 기능을 추가 구현하고자 issue를 reopen한다.
