### ISSUE TITLE
리뷰 생성 시 장소(`Place`)를 생성 및 저장하지 않도록 리팩토링

### ISSUE THREAD

**Issue by Wo-ogie** [Zelusik/server-main#271]
## 🔥 Issue
현재 리뷰 생성에 대한 로직은 다음과 같다.
- 장소 정보가 DB에 있는 경우: 장소 entity를 DB에서 조회한 후 리뷰 저장
- 장소 정보가 DB에 없는 경우: Scraping server에 요청해 장소 저장에 필요한 정보를 받아온 후 장소 entity 생성 및 저장. 그 후 리뷰 저장.

그러나 이러한 로직은 바람직하지 않다고 생각한다. 해당 로직은 "리뷰 생성 API"에 대한 로직이기 떄문에 리뷰 생성에 대한 역할만 수행하는 것이 바람직하며, 장소를 임의로 생성하여 저장하는 로직은 수행하지 않는 것이 좋다고 생각했다.

이에 프론트엔드 개발자들과 API 호출 로직에 대한 회의를 진행하였고 "리뷰 생성 API 호출 시에는 장소 정보가 DB에 들어있음"을 전제하고 API를 호출하도록 하였다.

이번 issue에서는 리뷰 생성  시 더 이상 장소(`Place`) entity를 생성하거나 저장하지 않도록 리팩토링한다.

## ✅ TODO
- [x] 리뷰 생성 시 장소(`Place`)를 생성 및 저장하지 않도록 리팩토링
  - [x] 리뷰 생성에 대한 business logic 수정
  - [x] 리뷰 생성 시 전달받는 요청 데이터 수정
